CREATE TABLE EAP_DEVICE (
	EAP_ID VARCHAR(64) PRIMARY KEY,
	EAP_NAME VARCHAR(64) NOT NULL,
	EAP_MODEL_VERSION VARCHAR(64) NOT NULL,
	EAP_SOFTWARE_VERSION VARCHAR(96) NOT NULL,
	EAP_MAC_ADDRESS_BINARY BIGINT,
	EAP_MAC_ADDRESS_VISUAL VARCHAR(32) NOT NULL,
	EAP_IPV4_ADDRESS_BINARY INT,
	EAP_IPV4_ADDRESS_VISUAL VARCHAR(32) NOT NULL,
	EAP_CREATE_TIME TIMESTAMP NOT NULL,
	EAP_ALIVE CHAR(1) NOT NULL
)
