CREATE TABLE `eap_device` (
  `EAP_ID` varchar(64) NOT NULL,
  `EAP_NAME` varchar(64) DEFAULT NULL,
  `EAP_MODEL_NAME` varchar(64) NOT NULL,
  `EAP_MODEL_VERSION` varchar(64) NOT NULL,
  `EAP_SOFTWARE_VERSION` varchar(96) NOT NULL,
  `EAP_MAC_ADDRESS` varchar(32) NOT NULL,
  `EAP_IPV4_ADDRESS` varchar(32) NOT NULL,
  `EAP_CREATE_TIME` bigint(20) NOT NULL,
  `EAP_MASK` varchar(32) DEFAULT NULL,
  `EAP_USER_NAME` varchar(32) NOT NULL,
  `EAP_PASSWORD_MD5` varchar(32) NOT NULL,
  PRIMARY KEY (`EAP_ID`),
  UNIQUE KEY `EAP_MAC_ADDRESS_UNIQUE` (`EAP_MAC_ADDRESS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `eap_log` (
  `ID` varchar(40) NOT NULL,
  `EAP_ID` varchar(45) NOT NULL,
  `COMMENT` blob,
  `CREATE_TIME` bigint(20) NOT NULL,
  `ACTION` varchar(45) NOT NULL,
  `DEST_ADDRESS` varchar(45) DEFAULT NULL,
  `DEST_PORT` int(11) DEFAULT NULL,
  `SOURCE_ADDRESS` varchar(45) DEFAULT NULL,
  `SOURCE_PORT` int(11) DEFAULT NULL,
  `EAP_MAC` varchar(45) NOT NULL,
  `TYPE` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `EAP_ID_FOREIGN_KEY_idx` (`EAP_ID`),
  KEY `CREATE_TIME_INDEX` (`CREATE_TIME`),
  CONSTRAINT `EAP_ID_FOREIGN_KEY` FOREIGN KEY (`EAP_ID`) REFERENCES `eap_device` (`EAP_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
